--------------------------------------------------------
--  Constraints for Table CITIZEN
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" MODIFY ("CITIZEN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" MODIFY ("CITIZEN_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" MODIFY ("NATIONAL_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_PK" PRIMARY KEY ("CITIZEN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_UK1" UNIQUE ("NATIONAL_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" MODIFY ("CITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" MODIFY ("GOVERNATE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("CITY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" ADD CONSTRAINT "CITY_UK1" UNIQUE ("CITY_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMITTEE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" MODIFY ("COMMITTEE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" MODIFY ("COMMITTEE_DATE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" MODIFY ("COMMITTEE_FUNCTION" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" MODIFY ("COMMITTEE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_PK" PRIMARY KEY ("COMMITTEE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" MODIFY ("ZONE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMITTEE_MEMBER
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" MODIFY ("COMMITTEE_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" MODIFY ("MEMBER_TITLE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ADD CONSTRAINT "COMMITTEE_MEMBER_PK" PRIMARY KEY ("COMMITTEE_MEMBER_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOM
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CUSTOM" MODIFY ("CUSTOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CUSTOM" ADD CONSTRAINT "CUSTOM_PK" PRIMARY KEY ("CUSTOM_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CUSTOM" MODIFY ("CUSTOM_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CUSTOM" ADD CONSTRAINT "CUSTOM_UK1" UNIQUE ("CUSTOM_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISABILITY
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" MODIFY ("DISABILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" MODIFY ("DISABILITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" MODIFY ("ACCEPTED" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" ADD CONSTRAINT "DISABILITY_PK" PRIMARY KEY ("DISABILITY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" ADD CONSTRAINT "DISABILITY_UK1" UNIQUE ("DISABILITY_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ADD  category VARCHAR2(100 BYTE) ;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ADD CONSTRAINT "DOCUMENT_TYPE_PK" PRIMARY KEY ("DOCUMENT_TYPE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ADD CONSTRAINT "DOCUMENT_TYPE_UK1" UNIQUE ("DOCUMENT_TYPE_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EQUIPMENT" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EQUIPMENT" MODIFY ("EQUIPMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_PK" PRIMARY KEY ("EQUIPMENT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_UK1" UNIQUE ("EQUIPMENT_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table EYE_MEASURE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" MODIFY ("MEASURE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" MODIFY ("MEASURE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ADD CONSTRAINT "EYE_MEASURE_PK" PRIMARY KEY ("MEASURE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ADD CONSTRAINT "EYE_MEASURE_UK1" UNIQUE ("MEASURE_TITLE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table EYE_REVEAL
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" MODIFY ("EYE_REVEAL_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" MODIFY ("RESULT" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" ADD CONSTRAINT "EYE_REVEAL_PK" PRIMARY KEY ("EYE_REVEAL_ID");
--------------------------------------------------------
--  Constraints for Table EYE_REVEAL_SETTING
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" MODIFY ("SETTING_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" MODIFY ("SETTING_RESULT" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" MODIFY ("LEFT_MEASURE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" MODIFY ("RIGHT_MEASURE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" ADD CONSTRAINT "EYE_REVEAL_SETTING_PK" PRIMARY KEY ("SETTING_ID");
--------------------------------------------------------
--  Constraints for Table GOVERNATE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" MODIFY ("GOVERNATE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" MODIFY ("GOVERNATE_CODE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" MODIFY ("GOVERNATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ADD CONSTRAINT "GOVERNATE_PK" PRIMARY KEY ("GOVERNATE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ADD CONSTRAINT "GOVERNATE_UK2" UNIQUE ("GOVERNATE_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ADD CONSTRAINT "GOVERNATE_UK1" UNIQUE ("GOVERNATE_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table OCCUPATION
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."OCCUPATION" MODIFY ("OCCUPATION_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."OCCUPATION" MODIFY ("OCCUPATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."OCCUPATION" ADD CONSTRAINT "OCCUPATION_PK" PRIMARY KEY ("OCCUPATION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."OCCUPATION" ADD CONSTRAINT "OCCUPATION_UK1" UNIQUE ("OCCUPATION_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" MODIFY ("CITIZEN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_PK" PRIMARY KEY ("REQUEST_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST_DOCUMENT
--------------------------------------------------------
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" MODIFY TYPE number ;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" RENAME COLUMN TYPE TO DOCUMENT_TYPE_ID;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT "REQUEST_DOCUMENT_FK2" FOREIGN KEY ("DOCUMENT_TYPE_ID")  REFERENCES "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ("DOCUMENT_TYPE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT REQUEST_DOCUMENT_UK1 UNIQUE (DOCUMENT_TYPE_ID, REQUEST_ID);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" MODIFY ("REQUEST_DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT "REQUEST_DOCUMENT_PK" PRIMARY KEY ("REQUEST_DOCUMENT_ID");
--------------------------------------------------------
--  Constraints for Table REQUEST_PAYMENT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_PAYMENT" MODIFY ("REQUEST_PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_PAYMENT" MODIFY ("RECEIPT_SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_PAYMENT" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_PAYMENT" ADD CONSTRAINT "REQUEST_PAYMENT_PK" PRIMARY KEY ("REQUEST_PAYMENT_ID");
--------------------------------------------------------
--  Constraints for Table REQUEST_STATUS
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_STATUS" MODIFY ("REQUEST_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_STATUS" MODIFY ("REQUEST_STATUS_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_STATUS" ADD CONSTRAINT "REQUEST_STATUS_PK" PRIMARY KEY ("REQUEST_STATUS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_STATUS" ADD CONSTRAINT "REQUEST_STATUS_UK1" UNIQUE ("REQUEST_STATUS_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST_TYPE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" MODIFY ("REQUEST_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" MODIFY ("REQUEST_TYPE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" ADD CONSTRAINT "REQUEST_TYPE_PK" PRIMARY KEY ("REQUEST_TYPE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" ADD CONSTRAINT "REQUEST_TYPE_UK1" UNIQUE ("REQUEST_TYPE_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYSTEM_AUDIT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" MODIFY ("PERFORMED_BY" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" ADD CONSTRAINT "SYSTEM_AUDIT_PK" PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYSTEM_ROLE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" ADD CONSTRAINT "SYSTEM_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" ADD CONSTRAINT "SYSTEM_ROLE_UK1" UNIQUE ("ROLE_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYSTEM_USER
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" ADD CONSTRAINT "SYSTEM_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAFFIC_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."TRAFFIC_MANAGEMENT" MODIFY ("TRAFFIC_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."TRAFFIC_MANAGEMENT" MODIFY ("TRAFFIC_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."TRAFFIC_MANAGEMENT" ADD CONSTRAINT "TRAFFIC_MANAGEMENT_PK" PRIMARY KEY ("TRAFFIC_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."TRAFFIC_MANAGEMENT" ADD CONSTRAINT "TRAFFIC_MANAGEMENT_UK1" UNIQUE ("TRAFFIC_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."USER_ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZONE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."ZONE" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."ZONE" MODIFY ("ZONE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."ZONE" ADD CONSTRAINT "ZONE_PK" PRIMARY KEY ("ZONE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."ZONE" ADD CONSTRAINT "ZONE_UK1" UNIQUE ("ZONE_NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITIZEN
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_FK1" FOREIGN KEY ("GOVERNATE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ("GOVERNATE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_FK2" FOREIGN KEY ("OCCUPATION_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."OCCUPATION" ("OCCUPATION_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_FK3" FOREIGN KEY ("CITY_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."CITY" ("CITY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITY" ADD CONSTRAINT "CITY_FK1" FOREIGN KEY ("GOVERNATE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ("GOVERNATE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMITTEE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK1" FOREIGN KEY ("MEMBER_ONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK2" FOREIGN KEY ("MEMBER_TWO_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK3" FOREIGN KEY ("MEMBER_THREE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK4" FOREIGN KEY ("MEMBER_FOUR_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK5" FOREIGN KEY ("MEMBER_FIVE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK6" FOREIGN KEY ("MEMBER_SIX_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ("COMMITTEE_MEMBER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ADD CONSTRAINT "COMMITTEE_FK7" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMITTEE_MEMBER
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."COMMITTEE_MEMBER" ADD CONSTRAINT "COMMITTEE_MEMBER_FK1" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISABILITY
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DISABILITY" ADD CONSTRAINT "DISABILITY_FK1" FOREIGN KEY ("EQUIPMENT_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."EQUIPMENT" ("EQUIPMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EYE_REVEAL
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" ADD CONSTRAINT "EYE_REVEAL_FK1" FOREIGN KEY ("LEFT_MEASURE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ("MEASURE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" ADD CONSTRAINT "EYE_REVEAL_FK2" FOREIGN KEY ("RIGHT_MEASURE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ("MEASURE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" ADD CONSTRAINT "EYE_REVEAL_FK3" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."REQUEST" ("REQUEST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EYE_REVEAL_SETTING
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" ADD CONSTRAINT "EYE_REVEAL_SETTING_FK1" FOREIGN KEY ("LEFT_MEASURE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ("MEASURE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL_SETTING" ADD CONSTRAINT "EYE_REVEAL_SETTING_FK2" FOREIGN KEY ("RIGHT_MEASURE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."EYE_MEASURE" ("MEASURE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOVERNATE
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" ADD CONSTRAINT "GOVERNATE_FK1" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK1" FOREIGN KEY ("CITIZEN_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."CITIZEN" ("CITIZEN_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK2" FOREIGN KEY ("TRAFFIC_MANAGEMENT_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."TRAFFIC_MANAGEMENT" ("TRAFFIC_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK3" FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."REQUEST_TYPE" ("REQUEST_TYPE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK4" FOREIGN KEY ("REQUEST_STATUS_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."REQUEST_STATUS" ("REQUEST_STATUS_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK5" FOREIGN KEY ("EYE_COMMITTEE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."COMMITTEE" ("COMMITTEE_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK6" FOREIGN KEY ("CUSTOM_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."CUSTOM" ("CUSTOM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT "REQUEST_DOCUMENT_FK1" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."REQUEST" ("REQUEST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST_PAYMENT
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_PAYMENT" ADD CONSTRAINT "REQUEST_PAYMENT_FK1" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."REQUEST" ("REQUEST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYSTEM_USER
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" ADD CONSTRAINT "SYSTEM_USER_FK1" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" ("USER_ID") ENABLE;
  ALTER TABLE "MOH_WORKFLOW_SCHEMA"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" ("ROLE_ID") ENABLE;



