--------------------------------------------------------
--  DDL for Table BONES_REVEAL
--------------------------------------------------------

  CREATE TABLE "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" 
   (	"BONES_REVEAL_ID" NUMBER NOT NULL ,
	"DISABILITY_ID"  NUMBER,
	"RESULT"	VARCHAR2(255 BYTE),
	"DESCRIPTION"	VARCHAR2(255 BYTE),
	"REVEAL_DONE"	NUMBER(1,0),
	"REQUEST_ID"	NUMBER NOT NULL
   );
CREATE UNIQUE INDEX "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL_PK" ON "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" ("BONES_REVEAL_ID");
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" ADD CONSTRAINT "BONES_REVEAL_PK" PRIMARY KEY ("BONES_REVEAL_ID")
 ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" MODIFY "RESULT" NULL;
=============================================================================
Change Date: 22-07-2019
-----------------------
-- this change is to make Citizen and Request is related to Zone
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD zone_id number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."CITIZEN" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" MODIFY ("ZONE_ID" NOT NULL ENABLE);
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_FK4" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;

ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD zone_id number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."REQUEST" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" MODIFY ("ZONE_ID" NOT NULL ENABLE);
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK7" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;


Change Date: 27-07-2019
-----------------------

ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" ADD ZONE_ID number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" MODIFY ("ZONE_ID" NOT NULL ENABLE);


UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'BONES_REVEAL' , ROLE_DESCRIPTION = '???????? ???? ??????' where ROLE_NAME = 'BONES';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'PAYMENTS_REGISTRATION' , ROLE_DESCRIPTION = '???????' where ROLE_NAME = 'CASHIER';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'CITIZEN_REQUEST_REGISTERING' , ROLE_DESCRIPTION = '????? ?????' where ROLE_NAME = 'CITIZEN';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'REQUEST_CONTINUE_REGISTERING' , ROLE_DESCRIPTION = '??????? ?????? ?????' where ROLE_NAME = 'CONTINUE_REGISTERING';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'EYE_REVEAL' , ROLE_DESCRIPTION = '???????? ???? ?????' where ROLE_NAME = 'EYE';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'EYE_REVEAL_RESULT_REGISTERING' , ROLE_DESCRIPTION = '????? ????? ??? ?????' where ROLE_NAME = 'MEDICAL_REGISTERING';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'REQUEST_APPROVING' , ROLE_DESCRIPTION = '?????? ???????' where ROLE_NAME = 'REQUESTS_APPROVER';
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" SET ROLE_NAME = 'REQUEST_REVIEWING' , ROLE_DESCRIPTION = '?????? ???????' where ROLE_NAME = 'REQUESTS_REVIEWER';


insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'BONES_REVEAL_RESULT_REGISTERING', '????? ????? ??? ??????');
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'RESULTS_PRINTING' ,'????? ???????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'RESULTS_VIEWING' ,'?????? ???????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'CITIZENS_REQUESTS_VIEWING' ,'????? ????? ?? ?????? ????????? ????????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'COMMITTEES_REGISTERING' ,'????? ?????? ? ???????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'SYSTEM_TABLES_MAINTENANCE' ,'????? ????? ??????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'DAILY_REPORTS_VIEWING' ,'?????? ???????? ???????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'STATISTIC_REPORTS_VIEWING' ,'?????? ???????? ???????' );
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'CITIZENS_DATA_EDITING' ,'????? ?????? ?????? ????????? ' );















======================================================================
31-07-2019
==========
insert into "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE"(ROLE_ID,ROLE_NAME, ROLE_DESCRIPTION) VALUES(SEQ_ROLE.NEXTVAL, 'SUPER_USER' ,'???? ???' );
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_ROLE" set ROLE_DESCRIPTION='???? ??????' where ROLE_NAME='ADMIN';
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."GOVERNATE" DROP COLUMN GOVERNATE_CODE;

--Adjusting Sequences:
-------------------
-- Governate
ALTER SEQUENCE SEQ_GOVERNATE  INCREMENT BY 80;
select SEQ_GOVERNATE.NEXTVAL from dual;
ALTER SEQUENCE SEQ_GOVERNATE  INCREMENT BY 1;
select SEQ_GOVERNATE.NEXTVAL from dual;
ALTER SEQUENCE SEQ_GOVERNATE  INCREMENT BY 1;
